<a id='Top'></a>
# Python common use cases 
The purpose of this is to demonstrate different use cases when I first learn python. 
- This is served as a reference to review Python syntax for a future job interview maybe. 

[**FILES_FOLDERS**](#FILES_FOLDERS) 

[**STRING**](#STRING)
[**FUNCTION**](#FUNCTION)
[**LIST**](#LIST)

[**CLASS**](#CLASS)
[**MODULE**](#MODULE)
[**MISC.**](#MISC.)

[**NumPy**](#NumPy)  [**Pandas**](#Pandas)

[**RegEx**](#RegEx)


**USEFUL LINK**
- Creating internal link
https://nbviewer.jupyter.org/github/rasbt/python_reference/blob/master/tutorials/table_of_contents_ipython.ipynb#top

## FILES_FOLDERS
[Back to Top](#Top)

In [1]:
import os
print(os.getcwd())

file = open('README.md','w') #override the old content
file.write('This is a README file for Python projects')
file.close()

file = open('README.md','a') #append instead of override
file.write('\n\nTesting\nTesting\nTesting')
file.close()

file = open('README.md','r')
print(file.read())
file.close()


/Users/spare
This is a README file for Python projects

Testing
Testing
Testing


In [2]:
import shelve 

shelf_file = shelve.open('mydata')
shelf_file['name'] = ['tom', 'nacy', 'mary']
shelf_file.close()

shelf_file = shelve.open('mydata')
shelf_file['name']
shelf_file.keys()
shelf_file.values()
# shelf_file.close()

ValuesView(<shelve.DbfilenameShelf object at 0x105f0de90>)

In [3]:
open_file = open('/Users/spare/Downloads/projects_python/f500.csv')

from csv import reader
moma_file = reader(open_file)
print(moma_file)
moma = list(moma_file)

### import os

In [4]:
import os

#current working directory is /Users/spare
print(os.getcwd()) #Current Working Directory
os.chdir(r'/Users/spare/Downloads') #Change Directory
print(os.getcwd())

print(os.sep) #root directory

os.path.abspath(r'5bx-plan.pdf') #regardless the file really exist or not
os.path.abspath(r'../5bx-plan.pdf')
os.path.exists(r'5bx-plan.pdf')
os.path.getsize(r'monk_manual_daily_sneakpeak.pdf')
os.listdir(r'/Users/spare/Downloads/projects_python')


/Users/spare
/Users/spare/Downloads
/


['Basics.ipynb',
 '.DS_Store',
 'AppleStore.csv',
 'googleplaystore_user_reviews.csv',
 'googleplaystore.csv',
 'HN_posts_year_to_Sep_26_2016.csv',
 'hacker_news.csv',
 'appleStore_description.csv',
 'f500.csv',
 'Artworks.csv',
 '.ipynb_checkpoints',
 'potus_visitors_2015.csv',
 'nyc_taxis.csv']

## STRING
[Back to Top](#Top)

https://docs.python.org/3/library/stdtypes.html#string-methods



In [5]:
#String index
string = "what is your name"
print(string[0])
print(string[0:1])
print(string[0:2])
print(string[-1])
print(string[-2:-1])

string = string+"?"
print(string)

w
w
wh
e
m
what is your name?


In [6]:
# 'Raw' string
print('c:\\downloads') #escape
print('OR:')
print(r'c:\downloads') #r = raw

c:\downloads
OR:
c:\downloads


In [7]:
import os
 
os.path.join('folder1','folder2')

'folder1/folder2'

In [8]:
print('dataquest'.startswith('Data'))
print('dataquest'.startswith('data'))

False
True


### String.format()

In [9]:
#.format()
# {} - template

output = "{}'s favorite number is {}".format("Kylie", 8)
print(output)

output = "{0}'s favorite number is {1}, {1} is {0}'s favorite number".format("Kylie", 8)
print(output)

template = "{name}'s favorite number is {num}, {num} is {name}'s favorite number"
output = template.format(name="Kylie", num="8")
print(output)


num = 32.554865
print("I own {pct}% of the company".format(pct=num))

Kylie's favorite number is 8
Kylie's favorite number is 8, 8 is Kylie's favorite number
Kylie's favorite number is 8, 8 is Kylie's favorite number
I own 32.554865% of the company


**Template & format**

In [10]:
#precision
template = "The approximate population of {0} is {1}"
out = template.format("India",1324000000)
print(out)

#Note: 
# : indicates start of format spec
template = "The approximate population of {0} is {1:,}"
out = template.format("India",1324000000) #***Have to define 'out' again when changing 'template'
print(out)

template = "The approximate population of {0} is {1:.2f}"
print(template.format("India",1324000000))

template = "The approximate population of {0} is {1:,.2f}"
#***don't use {1:.2f,}
print(template.format("India",1324000000))

The approximate population of India is 1324000000
The approximate population of India is 1,324,000,000
The approximate population of India is 1324000000.00
The approximate population of India is 1,324,000,000.00


In [11]:
#string.replace()
age1 = "I am thirty-one years old."
age1 = "I am thirty-one years old."
age3 = "You   are"

age1=age1.replace('old', 'YOUNG')
age2=age1.replace('one', 'TWO')
age3=age3.replace(' ','-')
print(age1)
print(age2)
print(age3)

I am thirty-one years YOUNG.
I am thirty-TWO years YOUNG.
You---are


**string.title() & string.lower()**
- Method returns a copy of the string with the first letter of each word transformed to uppercase (also known as title case).

In [12]:
my_string = "The cool thing about this string is that it has a CoMbInAtIoN of UPPERCASE and lowercase letters!"
print(my_string)

my_string.title()
print(my_string) 
my_string_title = my_string.title()
print(my_string_title)
my_string_title = my_string.lower()
print(my_string_title)

The cool thing about this string is that it has a CoMbInAtIoN of UPPERCASE and lowercase letters!
The cool thing about this string is that it has a CoMbInAtIoN of UPPERCASE and lowercase letters!
The Cool Thing About This String Is That It Has A Combination Of Uppercase And Lowercase Letters!
the cool thing about this string is that it has a combination of uppercase and lowercase letters!


### Sub-string

In [13]:
if "mike" in "michael":
    print("The substring was found.")
else:
    print("The substring was not found.")

The substring was not found.


**Split string.**
- string.split() means "throw away" and "separate", except for " ".

In [14]:
str_1  = "1991---1993"
str_1a = str_1.split("-")
print("str_1", str_1)
print("str_1a", str_1a)


str_2  = "2001   2002"
str_2a = str_2.split(" ")
print("\nstr_2=",str_2)
print("str_2a=",str_2a)

str_2a_new=[]
for index in str_2a:
    if index != "":
        #print(index)
        str_2a_new.append(int(index)) #don't use str_2a_new=...

print("str_2a_new=",str_2a_new,'\n')

date_string = '12/18/15 16:30'
print('date_string=',date_string)
date, time = date_string.split()
print(date)
print(time)
mnth, day, year = date.split('/')
print(mnth,',',day,',',year)
hr,mn = time.split(':')
print(hr,',',mn)



str_1 1991---1993
str_1a ['1991', '', '', '1993']

str_2= 2001   2002
str_2a= ['2001', '', '', '2002']
str_2a_new= [2001, 2002] 

date_string= 12/18/15 16:30
12/18/15
16:30
12 , 18 , 15
16 , 30


In [15]:
bad_string = ["Unknown", "n.d.", "before"]
string = "n.d."

for ele in bad_string:
    print(ele)
#     print(type(ele))
    if ele in string:
        print("bingo!!!\n")

st1 = "Early 1950"
print(st1)
st2 = st1.lower()
st1 = st1.lower()
print(st2)
print(st1)


Unknown
n.d.
bingo!!!

before
Early 1950
early 1950
early 1950


[Back to STRING](#STRING)



## FUNCTION
[Back to Top](#Top)



In [16]:
def some_func (in_var):
    local = in_var +1
    return local

result=some_func(5)
print('result=',some_func(5))
print('result=',result)


result= 6
result= 6


## LIST
[Back to Top](#Top)


In [17]:
#append
a = [1,2]
print('Originally, a=',a)
a.append(3) # don't use a=a.append()
print(a)

#pop
a.pop(1)
print(a)
print(a.pop())
print(a)

#add 2 lists
b = [10]
new_a = a + b
print (new_a)
print(len(new_a))

Originally, a= [1, 2]
[1, 2, 3]
[1, 3]
3
[1]
[1, 10]
2


## CLASS
[Back to Top](#Top)


In [18]:
class NewList():
    def return_list(self, input_list):
        return input_list

newlist = NewList()
result = newlist.return_list([1, 2, 3])

print(newlist)
print(result)

#CAN'T do this
#print(newlist([4,5,6]))

    

[1, 2, 3]


In [19]:
class MyClass():
    def __init__(self, string):
        print(string)

mc = MyClass("Hola!")

Hola!


In [20]:
class MyClass():
    def __init__(self, string):
        self.my_attribute = string

mc = MyClass("Hola!")
print(mc)
print(mc.my_attribute)


Hola!


In [21]:
class NewList():
    def __init__(self, initial_state):
        self.data   = initial_state

my_list = NewList([1,2,3,4,5]) #initialize
print(my_list)
print(my_list.data)

[1, 2, 3, 4, 5]


In [22]:
class NewList():
    def __init__(self, initial_state):
        self.data   = initial_state
        self.length = len(initial_state)
    
    def append(self, num):
        self.data += [num]
        
        #!!!It makes sense when you append and then calc_length() right away 
        # so self.length can be updated right away.
        self.calc_length() 
    
    def calc_length(self):
        self.length = len(self.data)
        

my_list = NewList([1, 2, 3, 4, 5]) #initialize
print(my_list)
print(my_list.data, my_list.length)

my_list.append(6)
print(my_list)
print(my_list.data, my_list.length)

print('\n')

fibonacci = NewList([1, 1, 2, 3, 5])
print(fibonacci.data, fibonacci.length)
fibonacci.append(8)
print(fibonacci.data, fibonacci.length) 
print('\n')
print(fibonacci.calc_length()) #'None' because the calc_length doesn't return anything
print(fibonacci.length)

[1, 2, 3, 4, 5] 5
[1, 2, 3, 4, 5, 6] 6


[1, 1, 2, 3, 5] 5
[1, 1, 2, 3, 5, 8] 6


None
6


[Back to CLASS](#CLASS)

# MODULE
[Back to Top](#Top)

In [23]:
# 1. Import the whole module by name. This is the most common method for importing a module.
# import the module
import csv

# definitions are available using the format
# module_name.definition_name
#csv.reader()


# 2. Import the whole module with an alias. This is especially useful if a module is long and we need to type it a lot.
# import the module with an alias
import csv as c

# definitions are available using the format
# alias.definition_name
#c.reader()


# 3. Import one or more definitions from the module by name. This is the technique we've used so far. This technique is useful if you want only a single or select definitions and don't want to import everything.
# import a single definition
from csv import reader

# the definition you imported is available
# by name
#reader()

# import multiple definitions
from csv import reader, writer

# the definitions you imported are available
# using the format definition_name
# reader()
# writer()


# 4. Import all definitions with a wildcard. This is useful if you want to import and use many definitions from a module.
# import all definitions
from csv import *

# all definitions from the module are
# available using the format definition_name
# reader()
# writer()
# get_dialect()

### datetime

[Back to Top](#Top)

In [24]:
import datetime as dt

#datetime.datetime(year, month, day, hour=0, minute=0, second=0)
ibm_founded = dt.datetime(1911, 6, 16)
man_on_moon = dt.datetime(1969, 7, 20, 20, 17)
print(ibm_founded)
print(type(ibm_founded))

print(man_on_moon)
print(type(man_on_moon))

test = dt.datetime(1, 1, 1)#year, month, day at least have to be 1
print(test)


1911-06-16 00:00:00
<class 'datetime.datetime'>
1969-07-20 20:17:00
<class 'datetime.datetime'>
0001-01-01 00:00:00


#### dt.datetime.time()

In [25]:
jfk_shot_dt = dt.datetime(1963, 11, 22, 12, 30)
print(jfk_shot_dt)
print(type(jfk_shot_dt))

jfk_shot_t = jfk_shot_dt.time()
print(jfk_shot_t)
print(type(jfk_shot_t))

1963-11-22 12:30:00
<class 'datetime.datetime'>
12:30:00
<class 'datetime.time'>


#### dt.datetime.strftime() >> str-f-time >> string format time

In [26]:
dt_object = dt.datetime(1984, 12, 24)
print(dt_object)
print(type(dt_object))

print('\n')
dt_string = dt_object.strftime("%d/%m/%Y")
print(dt_string)
print(type(dt_string))

dt_string = dt_object.strftime("%A %B %d at %I:%M %p")
print(dt_string)
print(type(dt_string))

1984-12-24 00:00:00
<class 'datetime.datetime'>


24/12/1984
<class 'str'>
Monday December 24 at 12:00 AM
<class 'str'>


#### dt.datetime.strptime() >> str-p-time >> string parse time

In [27]:
date_1_str = "24/12/1984"
print(date_1_str)
date_1_dt = dt.datetime.strptime(date_1_str, "%d/%m/%Y") #reflects the format in string
print(date_1_dt)
print(type(date_1_dt))

print('\n')
dt_str = "1900-01-01 08:00:00"
dt_datetime = dt.datetime.strptime(dt_str, "%Y-%m-%d %I:%M:%S")
print(dt_datetime)
print(type(dt_datetime))

print(dt_datetime.date())
print(type(dt_datetime.date()))
print(dt_datetime.time())
print(type(dt_datetime.time()))

print('Break it down:')
print(dt_datetime.year)
print(dt_datetime.month)
print(dt_datetime.hour)
print(dt_datetime.minute)
print(dt_datetime.second)
print(type(dt_datetime.second))

24/12/1984
1984-12-24 00:00:00
<class 'datetime.datetime'>


1900-01-01 08:00:00
<class 'datetime.datetime'>
1900-01-01
<class 'datetime.date'>
08:00:00
<class 'datetime.time'>
Break it down:
1900
1
8
0
0
<class 'int'>


#### dt.time()

In [28]:
#datetime.time(hour=0, minute=0, second=0, microsecond=0)

two_thirty = dt.time(14, 30)
print(two_thirty)
print(type(two_thirty))

five_sec_after_8am = dt.time(8,0,5)
print(five_sec_after_8am)
print(type(five_sec_after_8am))

print("\nCompare time:")
t1 = dt.time(15, 30)
t2 = dt.time(10, 45)

comparison = t1 > t2
print(comparison)
print(type(t1))

print('\n')
times = [
           dt.time(23, 30),
           dt.time(14, 45),
           dt.time(8, 0)
        ]

print(min(times))
print(max(times))

14:30:00
<class 'datetime.time'>
08:00:05
<class 'datetime.time'>

Compare time:
True
<class 'datetime.time'>


08:00:00
23:30:00


[Back to datetime](#datetime)

### datetime.timedelta

In [29]:
dt_1 = dt.datetime(1981, 1, 31)
dt_2 = dt.datetime(1984, 6, 28)
dt_3 = dt.datetime(2016, 5, 24)
dt_4 = dt.datetime(2001, 1, 1, 8, 24, 13)

#timedelta
answer_1 = dt_1 - dt_2
print(answer_1)
print(type(answer_1))

print('\n')
dt_list = [dt_1, dt_2, dt_3, dt_4]
min_time = min(dt_list)
print(min_time)

print('\n')
#Can do max and min in dictionary
length_counts = {
                  dt.timedelta(minutes=15): 21,
                  dt.timedelta(hours=3): 1,
                  dt.timedelta(seconds=45): 15
                }

min_length = min(length_counts)
print(min_length)
print(type(min_length))
print(isinstance(min_length, dt.timedelta))

-1244 days, 0:00:00
<class 'datetime.timedelta'>


1981-01-31 00:00:00


0:00:45
<class 'datetime.timedelta'>
True


[Back to MODULE](#MODULE)
[Back to datetime](#datetime)

## MISC.

In [30]:
a=[1,2]
print(isinstance(a,(list)))
print(isinstance(a,(int)))

True
False


In [31]:
a=1
print(type(a))
print(type(str(a)))

<class 'int'>
<class 'str'>


In [32]:
print(int(-3.0))
print(int(1956))


-3
1956


In [33]:
print(ord('–'))
print(ord('-'))

8211
45


[Back to Top](#Top)

## NumPy

NumPy library makes working with data easier. 
- Because we can easily work across multiple dimensions, our code is a lot easier to understand. 
- By using vectorized operations instead of loops, our code runs faster with larger data.

*NumPy Manual:
https://docs.scipy.org/doc/numpy-1.14.0/index.html*


In [34]:
import numpy as np
data_ndarray = np.array([10,20,30])

print(data_ndarray.mean())

20.0


### NumPy: Vectorized operations (Array)

In [35]:
data_ndarray = np.array([10,20,30])

print(data_ndarray)
print(type(data_ndarray))

print('\n')
print(data_ndarray + 10)
print(data_ndarray < 25)
print(type(data_ndarray < 25))


[10 20 30]
<class 'numpy.ndarray'>


[20 30 40]
[ True  True False]
<class 'numpy.ndarray'>


In [36]:
import csv
import numpy as np

f = open("/Users/spare/Downloads/projects_python/nyc_taxis.csv", "r")
taxi_list = list(csv.reader(f))

taxi_list = taxi_list[1:]
    
print('Print fist 3 lines as example:')
print(taxi_list[0:3])

# Convert all values to floats
# ***That's because NumPy ndarrays can contain only one datatype.***
converted_taxi_list = []
for row in taxi_list:
    converted_row = []
    for item in row:
        converted_row.append(float(item))
    converted_taxi_list.append(converted_row)

print('\nConvert list to array:')
taxi = np.array(converted_taxi_list)
print(taxi[0:1])
print

print('\n')
taxi_shape = taxi.shape
print(taxi_shape)


row_0 = taxi[0]
rows_391_to_500 = taxi[391:501]
row_21_column_5 = taxi[21, 5]

columns = [1,4,7]
columns_1_4_7= taxi[:,columns]
row_99_columns_5_to_8 =taxi[99,5:8]
rows_100_to_200_column_14=taxi[100:200,14]

Print fist 3 lines as example:
[['2016', '1', '1', '5', '0', '2', '4', '21.00', '2037', '52.00', '0.80', '5.54', '11.65', '69.99', '1'], ['2016', '1', '1', '5', '0', '2', '1', '16.29', '1520', '45.00', '1.30', '0.00', '8.00', '54.30', '1'], ['2016', '1', '1', '5', '0', '2', '6', '12.70', '1462', '36.50', '1.30', '0.00', '0.00', '37.80', '2']]

Convert list to array:
[[2.016e+03 1.000e+00 1.000e+00 5.000e+00 0.000e+00 2.000e+00 4.000e+00
  2.100e+01 2.037e+03 5.200e+01 8.000e-01 5.540e+00 1.165e+01 6.999e+01
  1.000e+00]]


(89560, 15)


In [37]:
# we'll compare against the first 5 rows only
taxi_first_five = taxi[:5]
# select these columns: fare_amount, fees_amount, tolls_amount, tip_amount
fare_components = taxi_first_five[:,9:13]

fare_sums_row = fare_components.sum(axis=1)
fare_sums_col = fare_components.sum(axis=0)
fare_sums     = fare_components.sum()

print(fare_sums_row)
print(type(fare_sums_row))
print(fare_sums_col)
print(type(fare_sums_col))
print(fare_sums)
print(type(fare_sums))

[69.99 54.3  37.8  32.76 18.8 ]
<class 'numpy.ndarray'>
[177.     6.     5.54  25.11]
<class 'numpy.ndarray'>
213.65
<class 'numpy.float64'>


[Back to NumPy](#NumPy)     [Back to Top](#Top)



### NumPy: Boolean Indexing

In a way this is similar to "associative array"

In [38]:
import numpy as np

f = open("/Users/spare/Downloads/projects_python/nyc_taxis.csv", "r")
taxi_list = list(csv.reader(f))
print('Print fist 3 lines of the LIST as example (from read csv to list):')
print(taxi_list[0:2])


print('\nUsing genfromtxt:')
taxi = np.genfromtxt('/Users/spare/Downloads/projects_python/nyc_taxis.csv', delimiter=',')
print(taxi)
print(type(taxi))
print(taxi.dtype)
taxi_shape = taxi.shape

print(taxi_shape)
print(type(taxi_shape))

print('\n')
x = np.array([1, 2, 3, 4])
print(x)
print(x.shape)

Print fist 3 lines of the LIST as example (from read csv to list):
[['pickup_year', 'pickup_month', 'pickup_day', 'pickup_dayofweek', 'pickup_time', 'pickup_location_code', 'dropoff_location_code', 'trip_distance', 'trip_length', 'fare_amount', 'fees_amount', 'tolls_amount', 'tip_amount', 'total_amount', 'payment_type'], ['2016', '1', '1', '5', '0', '2', '4', '21.00', '2037', '52.00', '0.80', '5.54', '11.65', '69.99', '1']]

Using genfromtxt:
[[      nan       nan       nan ...       nan       nan       nan]
 [2.016e+03 1.000e+00 1.000e+00 ... 1.165e+01 6.999e+01 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 8.000e+00 5.430e+01 1.000e+00]
 ...
 [2.016e+03 6.000e+00 3.000e+01 ... 5.000e+00 6.334e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 8.950e+00 4.475e+01 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 0.000e+00 5.484e+01 2.000e+00]]
<class 'numpy.ndarray'>
float64
(89561, 15)
<class 'tuple'>


[1 2 3 4]
(4,)


In [39]:
#remove header
pickup_month = taxi[:,1]
print('pickup_month (ndarray type) is:')
print(pickup_month)

print('\n')
# create BOOLEAN array of pickup_month==2
february_bool = pickup_month==2
print(february_bool)

# associate the boolean array back to pickup_month
february = taxi[february_bool]
print(february)
february_rides = february.shape
print(february_rides)
print(february_rides[0])

print('\n')
february = pickup_month[february_bool]
print(february)
february_rides = february.shape
print(february_rides)
print(february_rides[0])


pickup_month (ndarray type) is:
[nan  1.  1. ...  6.  6.  6.]


[False False False ... False False False]
[[2.016e+03 2.000e+00 1.000e+00 ... 0.000e+00 3.334e+01 2.000e+00]
 [2.016e+03 2.000e+00 1.000e+00 ... 2.000e+00 1.480e+01 1.000e+00]
 [2.016e+03 2.000e+00 1.000e+00 ... 6.350e+00 3.815e+01 1.000e+00]
 ...
 [2.016e+03 2.000e+00 2.900e+01 ... 0.000e+00 5.280e+01 2.000e+00]
 [2.016e+03 2.000e+00 2.900e+01 ... 6.350e+00 3.819e+01 1.000e+00]
 [2.016e+03 2.000e+00 2.900e+01 ... 3.000e+00 2.630e+01 1.000e+00]]
(13333, 15)
13333


[2. 2. 2. ... 2. 2. 2.]
(13333,)
13333


### Modify Array

In [40]:
taxi_modified = taxi.copy()
taxi_modified[28124,5] = 1
taxi_modified[:,0] = 16
taxi_modified[1800:1801,7]=taxi_modified[:,7].mean()

#For rows where the value of total_amount is less than 0, 
# use assignment to change the value to 0.
taxi_copy = taxi.copy()
total_amount = taxi_copy[:,13]
taxi_copy[total_amount<0] = 0

In [41]:
#numpy.zeros(shape, dtype=float, order='C')
zeros = np.zeros([taxi.shape[0], 1])
print(zeros)

print('\n')
#numpy.concatenate((a1, a2, ...), axis=0, out=None)
#Join a sequence of arrays along an existing axis.
taxi_modified = np.concatenate([taxi, zeros], axis=1)
print(taxi_modified)

print()
taxi_modified[taxi_modified[:,5]==2, 15] = 1
taxi_modified[taxi_modified[:,5]==3, 15] = 1
taxi_modified[taxi_modified[:,5]==5, 15] = 1
print(taxi_modified)


[[0.]
 [0.]
 [0.]
 ...
 [0.]
 [0.]
 [0.]]


[[      nan       nan       nan ...       nan       nan 0.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 6.999e+01 1.000e+00 0.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 5.430e+01 1.000e+00 0.000e+00]
 ...
 [2.016e+03 6.000e+00 3.000e+01 ... 6.334e+01 1.000e+00 0.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 4.475e+01 1.000e+00 0.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 5.484e+01 2.000e+00 0.000e+00]]

[[      nan       nan       nan ...       nan       nan 0.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 6.999e+01 1.000e+00 1.000e+00]
 [2.016e+03 1.000e+00 1.000e+00 ... 5.430e+01 1.000e+00 1.000e+00]
 ...
 [2.016e+03 6.000e+00 3.000e+01 ... 6.334e+01 1.000e+00 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 4.475e+01 1.000e+00 1.000e+00]
 [2.016e+03 6.000e+00 3.000e+01 ... 5.484e+01 2.000e+00 1.000e+00]]


[Back to NumPy](#NumPy)
[Back to Top](#Top)



## Pandas

Pandas is not so much a replacement for NumPy as an extension of NumPy.

[DATAFRAME objects](#Dataframe_objects) [Dataframe.loc[]](#Dataframe.loc[])

[SERIES objects](#Series_objects)
[Series.loc()](#Series.loc())
[Series.describe()](#Series.describe())
[Series.value_counts()](#Series.value_counts())

[Modification](#Modification)

**Useful references:**

**- https://honingds.com/blog/pandas-read_csv/**

### Dataframe_objects
- Dataframe = 2D Array

[Dataframe.loc[]](#Dataframe.loc())

#### Simple example

In [42]:
import pandas as pd

df = pd.DataFrame([[1, 2], [4, 5], [7, 8]],
      index   =['cobra', 'viper', 'sidewinder'],
      columns =['max_speed', 'shield'])

print(df)
print(type(df) )

print('\n----------------------')
# print(df.loc['max_speed']) --> can't do this 
print(df.loc['cobra'])

            max_speed  shield
cobra               1       2
viper               4       5
sidewinder          7       8
<class 'pandas.core.frame.DataFrame'>

----------------------
max_speed    1
shield       2
Name: cobra, dtype: int64


#### Import from file

In [43]:

f500 = pd.read_csv('/Users/spare/Downloads/projects_python/f500.csv', index_col=0)
f500.index.name = None

In [44]:
f500_type = type(f500)
print(f500_type)

f500_shape = f500.shape
print(f500_shape)

print('\nf500.info()=')
print(f500.info())

print('\n----------------------')
print('\f500.head(0)=')
f500_head_0 = f500.head(0)
print(f500_head_0)

print('\n----------------------')
print('\nf500.tail(1)=')
f500_tail_1 = f500.tail(1)
print(f500_tail_1)

<class 'pandas.core.frame.DataFrame'>
(500, 16)

f500.info()=
<class 'pandas.core.frame.DataFrame'>
Index: 500 entries, Walmart to AutoNation
Data columns (total 16 columns):
rank                        500 non-null int64
revenues                    500 non-null int64
revenue_change              498 non-null float64
profits                     499 non-null float64
assets                      500 non-null int64
profit_change               436 non-null float64
ceo                         500 non-null object
industry                    500 non-null object
sector                      500 non-null object
previous_rank               500 non-null int64
country                     500 non-null object
hq_location                 500 non-null object
website                     500 non-null object
years_on_global_500_list    500 non-null int64
employees                   500 non-null int64
total_stockholder_equity    500 non-null int64
dtypes: float64(3), int64(7), object(6)
memory usage: 66.4+ K

[Back to DATAFRAME](#Dataframe_objects)

#### Dataframe.loc()

In [45]:
india_df = f500.loc[f500['country'] =='India'] 
print(type(india_df),'\n')
print(india_df.head(2))


<class 'pandas.core.frame.DataFrame'> 

                     rank  revenues  revenue_change  profits  assets  \
Indian Oil            168     53562            -2.1   2960.0   42132   
Reliance Industries   203     46931             8.0   4458.9  108856   

                     profit_change               ceo            industry  \
Indian Oil                    72.7      Sanjiv Singh  Petroleum Refining   
Reliance Industries            5.6  Mukesh D. Ambani  Petroleum Refining   

                     sector  previous_rank country       hq_location  \
Indian Oil           Energy            161   India  New Delhi, India   
Reliance Industries  Energy            215   India     Mumbai, India   

                                 website  years_on_global_500_list  employees  \
Indian Oil           http://www.iocl.com                        23      34999   
Reliance Industries   http://www.ril.com                        14     140483   

                     total_stockholder_equity  
India

In [46]:
revenues_years = f500[["years_on_global_500_list","revenues"]]
print(type(revenues_years),'\n')
print('"years_on_global_500_list" and "revenues" =')
print(revenues_years)

print('\n----------------------')
ceo_to_sector = f500.loc[:,"ceo":"sector"]
print(type(ceo_to_sector))
print('\n "ceo" to "sector" =')
print(ceo_to_sector)

<class 'pandas.core.frame.DataFrame'> 

"years_on_global_500_list" and "revenues" =
                                years_on_global_500_list  revenues
Walmart                                               23    485873
State Grid                                            17    315199
Sinopec Group                                         19    267518
China National Petroleum                              17    262573
Toyota Motor                                          23    254694
...                                                  ...       ...
Teva Pharmaceutical Industries                         1     21903
New China Life Insurance                               2     21796
Wm. Morrison Supermarkets                             13     21741
TUI                                                   23     21655
AutoNation                                            12     21609

[500 rows x 2 columns]

----------------------
<class 'pandas.core.frame.DataFrame'>

 "ceo" to "sector" =
    

[Back to DATAFRAME](#Dataframe_objects)


[Back to Pandas](#Pandas)

**Using Dataframe on 'column'**

In [47]:
industries=f500.loc[:,"industry"]
print(type(industries),'\n')
print(industries)

print('\n----------------------')
print('OR:')
industries=f500["industry"]
print(industries)

print('\n----------------------')
print(industries[0])

print('\n----------------------')
industries_type=type(industries)
print(industries_type)
print(industries.shape)

<class 'pandas.core.series.Series'> 

Walmart                                     General Merchandisers
State Grid                                              Utilities
Sinopec Group                                  Petroleum Refining
China National Petroleum                       Petroleum Refining
Toyota Motor                             Motor Vehicles and Parts
                                               ...               
Teva Pharmaceutical Industries                    Pharmaceuticals
New China Life Insurance          Insurance: Life, Health (stock)
Wm. Morrison Supermarkets                    Food and Drug Stores
TUI                                               Travel Services
AutoNation                                    Specialty Retailers
Name: industry, Length: 500, dtype: object

----------------------
OR:
Walmart                                     General Merchandisers
State Grid                                              Utilities
Sinopec Group                    

[Back to DATAFRAME](#Dataframe_objects)

**Using Dataframe.loc[ ] on 'index'**

In [48]:
toyota = f500.loc["Toyota Motor"]
print(type(toyota))
print(toyota.shape)
print('\n')
print(toyota)

print('\n----------------------')
drink_companies = f500.loc[["Anheuser-Busch InBev", "Coca-Cola", "Heineken Holding"]]
print(type(drink_companies),'\n')
print(drink_companies)

#by both ROW and COLUMN
print('\n----------------------')
middle_companies=f500.loc["Tata Motors":"Nationwide" , "rank":"country"]
print(type(middle_companies),'\n')
print(middle_companies)

<class 'pandas.core.series.Series'>
(16,)


rank                                                   5
revenues                                          254694
revenue_change                                       7.7
profits                                          16899.3
assets                                            437575
profit_change                                      -12.3
ceo                                          Akio Toyoda
industry                        Motor Vehicles and Parts
sector                            Motor Vehicles & Parts
previous_rank                                          8
country                                            Japan
hq_location                                Toyota, Japan
website                     http://www.toyota-global.com
years_on_global_500_list                              23
employees                                         364445
total_stockholder_equity                          157210
Name: Toyota Motor, dtype: object

---------

#### Another example of DataFrame.loc[]

In [49]:
big_movers = f500.loc[ ["Aviva","HP","JD.com","BHP Billiton"] , ["rank","previous_rank"]]
print(type(big_movers))
print(big_movers)

print('\n----------------------')
bottom_companies=f500.loc["National Grid":"AutoNation", ["rank", "sector", "country"] ]
print(bottom_companies)

<class 'pandas.core.frame.DataFrame'>
              rank  previous_rank
Aviva           90            279
HP             194             48
JD.com         261            366
BHP Billiton   350            168

----------------------
                                       rank              sector  country
National Grid                           491              Energy  Britain
Dollar General                          492           Retailing      USA
Telecom Italia                          493  Telecommunications    Italy
Xiamen ITG Holding Group                494         Wholesalers    China
Xinjiang Guanghui Industry Investment   495         Wholesalers    China
Teva Pharmaceutical Industries          496         Health Care   Israel
New China Life Insurance                497          Financials    China
Wm. Morrison Supermarkets               498  Food & Drug Stores  Britain
TUI                                     499   Business Services  Germany
AutoNation                            

[Back to DATAFRAME](#Dataframe_objects)   [Back to Pandas](#Pandas)

### Series_objects
- Series = 1D Array

[Series.describe()](#Series.describe())
[Series.loc[]](#Series.loc[])
[Series.value_counts()](#Series.value_counts())


In [50]:
#Print header name as reference
print('\nf500.head(0)=')
f500_head_0 = f500.head(0)
print(f500_head_0)

print('\n----------------------')
rank = f500["rank"]
print(rank.shape)
print(type(rank))
print(rank.head(5))


f500.head(0)=
Empty DataFrame
Columns: [rank, revenues, revenue_change, profits, assets, profit_change, ceo, industry, sector, previous_rank, country, hq_location, website, years_on_global_500_list, employees, total_stockholder_equity]
Index: []

----------------------
(500,)
<class 'pandas.core.series.Series'>
Walmart                     1
State Grid                  2
Sinopec Group               3
China National Petroleum    4
Toyota Motor                5
Name: rank, dtype: int64


#### Series.describe() 

In [51]:
prev_rank=f500["previous_rank"]
prev_rank_desc=prev_rank.describe()
print(prev_rank_desc)

count    500.000000
mean     222.134000
std      146.941961
min        0.000000
25%       92.750000
50%      219.500000
75%      347.250000
max      500.000000
Name: previous_rank, dtype: float64


#### Series.max() Series.min() Series.mean() Series.median() Series.mode() Series.sum()

In [52]:
max_f500 = f500.max(numeric_only=1)
print(max_f500)
print('\n')
print(max_f500.shape)

rank                            500.0
revenues                     485873.0
revenue_change                  442.3
profits                       45687.0
assets                      3473238.0
profit_change                  8909.5
previous_rank                   500.0
years_on_global_500_list         23.0
employees                   2300000.0
total_stockholder_equity     301893.0
dtype: float64


(10,)


[Back to SERIES](#Series_objects) [Back to Pandas](#Pandas)


#### Series.loc[]

In [53]:
countries = f500['country']
print(type(countries))
print(countries)
print('\n----------------------')

print(countries.loc['State Grid'] )
print(countries.loc['Walmart'])

<class 'pandas.core.series.Series'>
Walmart                               USA
State Grid                          China
Sinopec Group                       China
China National Petroleum            China
Toyota Motor                        Japan
                                   ...   
Teva Pharmaceutical Industries     Israel
New China Life Insurance            China
Wm. Morrison Supermarkets         Britain
TUI                               Germany
AutoNation                            USA
Name: country, Length: 500, dtype: object

----------------------
China
USA


[Back to SERIES](#Series_objects) [Back to Pandas](#Pandas)

#### Series.value_counts()

In [54]:
countries = f500["country"]
print(type(countries))

countries_counts = countries.value_counts()
print(countries_counts[0:10])
print('\n', type(countries_counts) )

<class 'pandas.core.series.Series'>
USA            132
China          109
Japan           51
Germany         29
France          29
Britain         24
South Korea     15
Switzerland     14
Netherlands     14
Canada          11
Name: country, dtype: int64

 <class 'pandas.core.series.Series'>


In [55]:
india = countries_counts.loc['India']
print("""Number of 'country' are 'India':""")
print(india)
print(type(india))

print('\n----------------------')
north_america = countries_counts.loc[["USA","Canada","Mexico"]]
print(type(north_america))
print(north_america)

#Using Series.loc[]
print('----------------------')
print('OR the shortcut (using Series.loc[]) would be:')
print("""     f500['country'].value_counts().loc[["USA","Canada","Mexico"]  \n""")
north_america = f500['country'].value_counts().loc[ ["USA","Canada","Mexico"] ]
print(north_america)

Number of 'country' are 'India':
7
<class 'numpy.int64'>

----------------------
<class 'pandas.core.series.Series'>
USA       132
Canada     11
Mexico      2
Name: country, dtype: int64
----------------------
OR the shortcut (using Series.loc[]) would be:
     f500['country'].value_counts().loc[["USA","Canada","Mexico"]  

USA       132
Canada     11
Mexico      2
Name: country, dtype: int64


[Back to SERIES](#Series_objects) [Back to Pandas](#Pandas)

#### Another example combines Series.loc[] and Series.value_counts

In [56]:
previous_rank = f500["previous_rank"]
print(previous_rank)

print('\n----------------------')
previous_rank_counts = previous_rank.value_counts()
print(previous_rank_counts)

print('\n----------------------')
zero_previous_rank = previous_rank_counts.loc[0]
print(zero_previous_rank)

print("""\nOR we can just do:\n zero_previous_rank=f500.["previous_rank"].value_counts().loc[0]""")
print(f500["previous_rank"].value_counts().loc[0])

Walmart                             1
State Grid                          2
Sinopec Group                       4
China National Petroleum            3
Toyota Motor                        8
                                 ... 
Teva Pharmaceutical Industries      0
New China Life Insurance          427
Wm. Morrison Supermarkets         437
TUI                               467
AutoNation                          0
Name: previous_rank, Length: 500, dtype: int64

----------------------
0      33
159     1
147     1
148     1
149     1
       ..
321     1
322     1
323     1
324     1
235     1
Name: previous_rank, Length: 468, dtype: int64

----------------------
33

OR we can just do:
 zero_previous_rank=f500.["previous_rank"].value_counts().loc[0]
33


[Back to SERIES](#Series_objects) [Back to Pandas](#Pandas)

#### Modification & Boolean

In [57]:
print(f500["ceo"].loc['Dow Chemical'])
f500["ceo"].loc['Dow Chemical'] = 'Jim Fitterling'
print(f500["ceo"].loc['Dow Chemical'])

Andrew N. Liveris
Jim Fitterling


/Users/spare/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:205: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)


In [58]:
motor_bool = f500["industry"] == "Motor Vehicles and Parts"
motor_countries = f500.loc[motor_bool,"country"]
print(motor_countries.shape)
print(motor_countries[0:5])

print("""\n\nOR we can just use: \n  f500.loc[f500["industry"]=="Motor Vehicles and Parts", "country"] """)
print(f500.loc[f500["industry"]=="Motor Vehicles and Parts","country"][0:5])

print('\n***NOTE: ONLY COUPLE LINES ARE PRINTED')

(34,)
Toyota Motor        Japan
Volkswagen        Germany
Daimler           Germany
General Motors        USA
Ford Motor            USA
Name: country, dtype: object


OR we can just use: 
  f500.loc[f500["industry"]=="Motor Vehicles and Parts", "country"] 
Toyota Motor        Japan
Volkswagen        Germany
Daimler           Germany
General Motors        USA
Ford Motor            USA
Name: country, dtype: object

***NOTE: ONLY COUPLE LINES ARE PRINTED


In [59]:
import numpy as np
import pandas as pd

f500 = pd.read_csv('/Users/spare/Downloads/projects_python/f500.csv', index_col=0)
f500.index.name = None

# Create a Series of 1 dimention array ('previous_rank' column only) that has 'previous_rank'==0
# - f500.loc[] --> location (value)
# - f500["previous_rank"]==0 --> locate "boolean" column
# - "previous_rank" --> only "take" that column
a = f500.loc[f500["previous_rank"] ==0, "previous_rank"]
print(a.head())
print(type(a))
print(a.shape)
print(a[0]) #a is an array


print('\n----------------------')
prev_rank_before = f500["previous_rank"].value_counts(dropna=False)
print(prev_rank_before.head())

print('\n')
f500.loc[f500["previous_rank"]==0, "previous_rank"] = np.nan
prev_rank_after = f500["previous_rank"].value_counts(dropna=False)
print(prev_rank_after.head())

print('\n')
f500['rank_change'] = f500['rank'] - f500['previous_rank']
rank_change = f500['rank_change']
print(rank_change.head())
print(rank_change.describe())

#Create series 'industry_usa', containing counts of the two most common values 
#  in the industry column for companies headquartered in the USA.
print('\n----------------------')
industry_usa = f500.loc[f500['country']=='USA', 'industry'].value_counts().head(2)
print(industry_usa)

#Create series 'sector_china' containing counts of the three most common values
#  in the sector column for companies headquartered in the China.
print('\n----------------------')
sector_china = f500.loc[f500['country']=='China', 'sector'].value_counts().head(3)
print(sector_china)

#Create a float object, mean_employees_japan, containing the mean (average) 
#  number of employees for companies headquartered in Japan.
print('\n----------------------')
mean_employees_japan = f500.loc[f500['country']=='Japan','employees'].mean()
print(mean_employees_japan)

Legal & General Group     0
Uniper                    0
Dell Technologies         0
Anbang Insurance Group    0
Albertsons Cos.           0
Name: previous_rank, dtype: int64
<class 'pandas.core.series.Series'>
(33,)
0

----------------------
0      33
159     1
147     1
148     1
149     1
Name: previous_rank, dtype: int64


NaN      33
471.0     1
234.0     1
125.0     1
166.0     1
Name: previous_rank, dtype: int64


Walmart                     0.0
State Grid                  0.0
Sinopec Group              -1.0
China National Petroleum    1.0
Toyota Motor               -3.0
Name: rank_change, dtype: float64
count    467.000000
mean       3.533191
std       44.293603
min     -226.000000
25%      -10.000000
50%        2.000000
75%       21.000000
max      199.000000
Name: rank_change, dtype: float64

----------------------
Banks: Commercial and Savings               8
Insurance: Property and Casualty (Stock)    7
Name: industry, dtype: int64

----------------------
Financials     25
E

[Back to Pandas](#Pandas) [Back to Top](#Top)

## RegEx
[Grouping](#Grouping)
[Wildcards](#Wildcards)

[Find_and_Replace](#Find_and_Replace)



#### RegEx method with .complile() .search() .findall()

In [60]:
import re

In [61]:
message = "Call me 415-333-1233 or 343-343-2343"

phoneNumRegex = re.compile(r'\d\d\d-\d\d\d-\d\d\d\d') #r means raw
print(type(phoneNumRegex))

print('\nUsing .search():')
match_object = phoneNumRegex.search(message)
print(type(match_object))
print(match_object)
print(match_object.group())

print('\nUsing .findall():')
match_object = phoneNumRegex.findall(message)
print(type(match_object))
print(match_object)

<class 're.Pattern'>

Using .search():
<class 're.Match'>
<re.Match object; span=(8, 20), match='415-333-1233'>
415-333-1233

Using .findall():
<class 'list'>
['415-333-1233', '343-343-2343']


#### Grouping

In [62]:
message = "Call me 415-333-1233 or (415) 343-2343"

phoneNumRegex = re.compile(r'(\d\d\d)-(\d\d\d-\d\d\d\d)')
mo = phoneNumRegex.search(message)
print(mo.group())
print(mo.group(1))
print(mo.group(2))

print('-------------------------')
phoneNumRegex = re.compile(r'\(\d\d\d\) \d\d\d-\d\d\d\d')
mo = phoneNumRegex.search(message)
print(mo.group())


415-333-1233
415
333-1233
-------------------------
(415) 343-2343


#### Using [] instead of pipe |

In [63]:
regex_comp=re.compile(r'bat(man|mobile|coper)')
mo = regex_comp.search('who is batman?')
print(mo.group())

mo = regex_comp.search('batmobile is broken?')
print(mo.group())

mo = regex_comp.search('batwoman is driving a car?')
print(mo==None)

batman
batmobile
True


In [64]:
lyrics = """11 Pipers Piping, 10 Lords a Leaping, 9 Ladies Dancing, 8 Maids a Milking
, 7 Swans a Swimming, 6 Geese a Laying, 5 Golden Rings, 4 Calling Birds, 3 French Hens
, 2 Turtle Doves and a Partridge in a Pear Tree"""

print('\n')
regex_comp2 = re.compile(r'[aieuoAIEUO]{2}') #similar to (a|i|...)
mo = regex_comp2.findall(lyrics)
print(mo)

print('\n')
regex_comp3 = re.compile(r'[^aieuoAIEUO]{2}') 
# ^ = NOT, in this case, otherwise ^ begining of the string
mo = regex_comp3.findall(lyrics)
print(mo)



['ea', 'ie', 'ai', 'ee', 'ea', 'ee']


['11', ' P', 'rs', ' P', 'ng', ', ', '10', ' L', 'rd', 's ', ' L', 'ng', ', ', '9 ', 's ', 'nc', 'ng', ', ', '8 ', 'ds', ' M', 'lk', 'ng', '\n,', ' 7', ' S', 'ns', ' S', 'mm', 'ng', ', ', '6 ', ' L', 'ng', ', ', '5 ', 'ld', 'n ', 'ng', 's,', ' 4', ' C', 'll', 'ng', ' B', 'rd', 's,', ' 3', ' F', 'nc', 'h ', 'ns', '\n,', ' 2', ' T', 'rt', ' D', 's ', 'nd', ' P', 'rt', 'dg', 'n ', ' P', 'r ', 'Tr']


[Back to RegEx](#RegEx) [Back to Top](#Top)

#### Wildcards
##### Match repetition using Wildcard ? + * {} 
- ? is 0 or 1 time
- \+ is 1 or more time
- \* is 0 or more time
- . is any characters except newline
- {} is number of repetition

In [65]:
regex_comp = re.compile(r'(\d\d\d-)?\d\d\d-\d\d\d\d')

mo = regex_comp.search("My phone number is 217-721-3126. Call me.")
print(mo.group())
mo = regex_comp.search("My phone number is 721-3126. Call me.")
print(mo.group())


217-721-3126
721-3126


In [66]:
regex_comp = re.compile(r'(ha){1,3}')
mo = regex_comp.search("hahahahaha")
print(mo.group()) #return the MOST match - "GREEDY"

print('-------------------------------')
regex_comp = re.compile(r'(ha){1,3}?')
mo = regex_comp.search("hahahahaha")
print(mo.group()) #return the LEAST depending on ? - "non-GREEDY"

mo = regex_comp.search("hello")
print(mo==None)


hahaha
-------------------------------
ha
True


#### Different types of matching characters
For example, 
- \d for digits
- \s for space 
- \w for word character

In [67]:
lyrics = """11 Pipers Piping, 10 Lords a Leaping, 9 Ladies Dancing, 8 Maids a Milking
, 7 Swans a Swimming, 6 Geese a Laying, 5 Golden Rings, 4 Calling Birds, 3 French Hens
, 2 Turtle Doves and a Partridge in a Pear Tree"""

regex_comp1 = re.compile(r'\d+\s\w*')
mo = regex_comp1.findall(lyrics)
print(mo)


['11 Pipers', '10 Lords', '9 Ladies', '8 Maids', '7 Swans', '6 Geese', '5 Golden', '4 Calling', '3 French', '2 Turtle']


#### Begin & End of line using ^ and \$

In [68]:
regex = re.compile(r'^Hello')
mo = regex.findall('Hello there')
print(mo)

mo = regex.findall('Just say Hello')
print(mo)

regex = re.compile(r'Hello$')
mo = regex.findall('Just say Hello')
print(mo)


print('\n')
regex = re.compile(r'^\d+$')
mo = regex.findall('1233432423432')
print(mo)

mo = regex.findall('12334x32423432')
print(mo)

['Hello']
[]
['Hello']


['1233432423432']
[]


#### Combine Wild card . and *
- \. is any single character, EXCEPT new line.

In [69]:
string = 'First name: Leon, Last name: Truong'
regex = re.compile(r'(First name: (.*), Last name: (.*))' ) #.*  is GREEDY
mo = regex.findall(string)
print(mo)
print(type(mo))
print(len(mo))
print(mo[0][0])
print(type(mo[0]))

print('\n-------------')
print('non-GREEDY match:')
string = '<to serve human> for dinner.>'
regex = re.compile(r'<.*?>') #.*? non-GREEDY
mo = regex.findall(string)
print(mo)

print('\nGREEDY match:')
regex = re.compile(r'<.*>') #.*? GREEDY
mo = regex.findall(string)
print(mo)


[('First name: Leon, Last name: Truong', 'Leon', 'Truong')]
<class 'list'>
1
First name: Leon, Last name: Truong
<class 'tuple'>

-------------
non-GREEDY match:
['<to serve human>']

GREEDY match:
['<to serve human> for dinner.>']


[Back to RegEx](#RegEx) [Back to Top](#Top)

#### Find_and_Replace
- re.Pattern.sub()

In [70]:
string = "Player Nathan has kicked Player Tom butt!"
pat = re.compile(r'Player \w+ ')
print(type(pat))
mo = pat.findall(string)
print(mo)

new_string = pat.sub('NoName ', string)
print(new_string)


print('\n')
pat = re.compile(r'Player (\w)\w+ ')
mo = pat.findall(string)
print(mo)
new_string = pat.sub(r'\1--- ',string) #\1 means group 1
print(new_string)


<class 're.Pattern'>
['Player Nathan ', 'Player Tom ']
NoName has kicked NoName butt!


['N', 'T']
N--- has kicked T--- butt!


#### re.VERBOSE
- Can use # inside matching pattern for notation.

In [71]:
#pat = re.compile(r'\d\d\d-\d\d\d-\d\d\d\d')
pat = re.compile(r'''\d\d\d-          #area code
                     \d\d\d-\d\d\d\d  #the rest of the number''', re.VERBOSE|re.IGNORECASE)

message = "Call me 415-333-1233 or 343-343-2343"
print(pat.findall(message))

['415-333-1233', '343-343-2343']


[Back to RegEx](#RegEx) [Back to Top](#Top)